# Generated by Django 5.1.4 on 2024-12-26 23:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('madre', models.CharField(max_length=100)),
                ('padre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cruce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_insem', models.DateField()),
                ('fecha_actual', models.DateField(default=datetime.date.today)),
                ('dias_transcurridos', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_parto_estimada', models.DateField(blank=True, null=True)),
                ('perro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cruces', to='perros.perro')),
            ],
        ),
    ]
