# Generated by Django 5.1.6 on 2025-03-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cruce',
            name='fecha_actual',
            field=models.DateField(auto_now=True),
        ),
    ]
